spring.application.name=tecnico-api
spring.flyway.enabled=false
spring.datasource.url=jdbc:mysql://localhost:3306/db_tecnico
spring.datasource.username = root
spring.datasource.password = 

spring.jpa.hibernate.ddl-auto=create-drop
